mode: "dev"
port: 8081

log:
  level: "debug"
  filename: "./log/web_back.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: aerfa2014
  db: web_back
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: 127.0.0.1
  port: 16379
  db: 0

jwt:
  secretKey: abc